.DEFAULT_GOAL := build-run

clean:
		gradlew.bat clean

build:
	gradlew.bat build

lint:
	gradlew.bat checkstyleMain checkstyleTest

test:
	gradlew.bat test

report:
	gradlew.bat jacocoTestReport

.PHONY: build
